### ISSUE TITLE
table format is ugly when there are few apps

### ISSUE THREAD

**Issue by frehner** [CanopyTax/single-spa-inspector#11]
![screen shot 2019-02-21 at 11 54 14 am](https://user-images.githubusercontent.com/3054066/53193949-7f320e00-35cf-11e9-8125-811d5efd1520.png)
I rest my case.

I think it's because the table is height 100%.

This would be a great beginner bug to work on if anyone is interested.

**Comment by filoxo** [comment]
I'll take this one.
