### ISSUE TITLE
Have overlays look for container div with default id

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-inspector#17]
Helper libraries such as single-spa-vue, single-spa-angular, and single-spa-react all implement a default dom element getter now that appends a div to the dom with an html id that follows a certain convention.

Single-spa-inspector could check if that html id exists when looking for a div to append overlays to. This would be awesome because then single-spa users don't even have to do `export const devtools` from their apps. See related https://github.com/CanopyTax/single-spa-react/issues/51.

**Comment by frehner** [comment]
ooh that's a great idea. Should be pretty easy as well.

I'll add it in when I get back while also taking a look at implementing some override behaviors in the extension.

**Comment by joeldenning** [comment]
@frehner any update on this? I am keen on seeing this in. If you can't get to it soon I might have some time for it.

**Comment by frehner** [comment]
Ah I forgot about it.

**Comment by filoxo** [comment]
I might have some time soon to work on this as well.
