### ISSUE TITLE
Overlays do not resize dynamically

### ISSUE THREAD

**Issue by filoxo** [CanopyTax/single-spa-inspector#36]
When an app resizes, the overlay does not until it is removed and readded. In this example, navbar-ui had had a banner displayed above it. When I dismissed that banner, the overall size of navbar-ui changed but the overlay is still the original size.

![Screen Shot 2019-10-11 at 12 23 55 PM](https://user-images.githubusercontent.com/4202993/66675244-2973aa00-ec22-11e9-9bbe-4fdbf6f624dc.png)

**Comment by filoxo** [comment]
Also happens with page resize, which is most commonly happens when resizing the devtools with the page as well.

**Comment by filoxo** [comment]
[ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) sounds like its perfect for this.

**Comment by joeldenning** [comment]
No edge and safari support is tough. Couldn't it be done with just the window `resize` event? https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event

**Comment by filoxo** [comment]
web-ext doesn't support edge or safari so I'm not sure there's much value in targeting them.

**Comment by filoxo** [comment]
Oh yea, and also re: window resize, that wouldn't work if the element itself changed in size. For example, my navbar is showing a dismissible banner and if the user does dismiss it, the size of navbar changes but the overlays didn't redraw.

**Comment by joeldenning** [comment]
I see. Then yeah sounds like your suggested implementation would be a good one. 👍

**Comment by frehner** [comment]
I'm convinced as well. Good proposal, @filoxo
