### ISSUE TITLE
automate extension update process

### ISSUE THREAD

**Issue by frehner** [CanopyTax/single-spa-inspector#9]
currently I'm just doing it manually. it would be great to add a script that does it for us though.

For Chrome, I think it's possible to do that at the moment.

For FF, I don't entirely know if the whole process can be automated at the moment or not. See this thread and comment: https://github.com/mozilla/web-ext/issues/804#issuecomment-426670076

**Comment by filoxo** [comment]
I'm playing with a node script for this.

**Comment by filoxo** [comment]
Nevermind, I'll probably use this instead https://github.com/LinusU/wext-shipit

**Comment by frehner** [comment]
now that I'm older and wiser (and have played around with this more), it's actually not going to be as hard as I thought. 

FF updates are already built-in using the script outlined in the readme, so you'd only have to put in a little bit of work to add Chrome :D
